/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sem6archivoestudiantecorregido;

import java.io.*; // se puede importar cualquier libreria io y se le pone el * en vez de la ultima palabra o parte
import javax.swing.JOptionPane;

/**
 *
 * @author Randall Segura
 */
public class Catalogo extends javax.swing.JFrame {

    private String cedula, nombre, curso;   //se crean las variables
    private double calificacion;

    /**
     * Creates new form Catalogo
     */
    public Catalogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        cmbCurso = new javax.swing.JComboBox<>();
        txtCalificacion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de Estudiantes");
        setResizable(false);

        jToolBar1.setRollover(true);

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setFocusable(false);
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAgregar);

        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setFocusable(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEditar);

        btnConsultar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.setFocusable(false);
        btnConsultar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnConsultar);

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setFocusable(false);
        btnEliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnEliminar);

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setFocusable(false);
        btnLimpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLimpiar);

        jLabel1.setText("Cedula");

        jLabel2.setText("Curso");

        jLabel3.setText("Nombre");

        jLabel4.setText("Calificacion");

        cmbCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escoja una opcion", "Prog. Basica", "Intro. Prog.", "Intro. Info.", "Estruc. Datos", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCedula))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(30, 30, 30)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(cmbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void agregar() {

        try {
            //capturar los datos de los campos para guardarlos en los archivos
            cedula = txtCedula.getText();
            nombre = txtNombre.getText();
            curso = cmbCurso.getSelectedItem().toString();
            calificacion = Double.parseDouble(txtCalificacion.getText());
            //abrir el archivo en modo append para concatenar para agregar los datos sin borrar los anteriores
            //este true sirve para que agregue un nuevo estudiante al archivo, sin borrar los anteriores
            try (DataOutputStream dos = new DataOutputStream(new FileOutputStream("Calificacion.dat", true))) { 
                //Escribir los datos en el archivo
                //Para los string se usa writeUTF que es texto enriquecido, para double se usa writeDouble
                dos.writeUTF(cedula);
                dos.writeUTF(nombre);
                dos.writeUTF(curso);
                dos.writeDouble(calificacion);
            }
            //Mensaje de exito al guardar los datos
            JOptionPane.showMessageDialog(null, "Datos agregados correctamente", "Datos Guardados", JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException e) {
            //Captura problemas de entrada/salida: archivo inaccesible, disco lleno, carpeta no encontrada, etc.
            JOptionPane.showMessageDialog(null, "Error al guardar los datos", "Error", JOptionPane.ERROR_MESSAGE);

        } catch (NumberFormatException e) {
            //Captura errores si el valor en el campo de calificación no es un número válido.
            JOptionPane.showMessageDialog(null, "Calificacion no valida", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }

    private void guardarDatos(String datos) {
        try (DataOutputStream dos = new DataOutputStream(new FileOutputStream("Calificacion.dat"))) {
            String lineas[] = datos.split("\n");
            for (int i = 0; i < lineas.length; i += 4) { //avanza de 4 en 4 porque cada estudiante tiene 4 datos
                if (i + 3 < lineas.length) {// asegura que haya al menos 4 lineas para evitar errores si el arreglo tiene  lineas incompletas
                    dos.writeUTF(lineas[i]); //cedula
                    dos.writeUTF(lineas[i + 1]); //nombre
                    dos.writeUTF(lineas[i + 2]); //curso
                    dos.writeDouble(Double.parseDouble(lineas[i + 3])); //calificacion

                }

            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error al guardar los datos", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }
    
    
    

    public void editar() {
        String cedulaBuscar = txtCedula.getText();
        StringBuilder contenido = new StringBuilder();
        boolean encontrado = false;

        try (DataInputStream dis = new DataInputStream(new FileInputStream("calificacion.dat"))) {
            while (true) {
                String cedula = dis.readUTF();
                String nombre = dis.readUTF();
                String curso = dis.readUTF();
                double calificacion = dis.readDouble();

                if (cedula.equals(cedulaBuscar)) { // si la cedula del archivo es igual a la buscada
                    //actualiza los datos encontrados en los campos 
                    //captura los datos encontradoss
                    nombre = txtNombre.getText();
                    curso = cmbCurso.getSelectedItem().toString();
                    calificacion = Double.parseDouble(txtCalificacion.getText());
                    encontrado = true; // se encontro la cedula

                }
                //los guarda en un string - cadena
                contenido.append(cedula).append("\n").
                        append(nombre).append("\n").
                        append(curso).append("\n").
                        append(calificacion).append("\n");
            }
        } catch (EOFException e) {
            //fin del archivo alcanzado, se usa como señal para salir del while (true)

            if (encontrado) {
                guardarDatos(contenido.toString());
                JOptionPane.showMessageDialog(null, "Datos guardados correctamente", "Datos editados", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Error, estudiante no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error al editar los datos", "Error", JOptionPane.ERROR_MESSAGE);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error, calificacion no valida", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void consultar() {
        String cedulaBuscar = txtCedula.getText();
        boolean encontrado = false;
        try (DataInputStream dis = new DataInputStream(new FileInputStream("calificacion.dat"))) {
            
            while (true) {
                String cedula = dis.readUTF();
                String nombre = dis.readUTF();
                String curso = dis.readUTF();
                double calificacion = dis.readDouble();

                if (cedula.equals(cedulaBuscar)) { // si la cedula del archivo es igual a la buscada
                    //si encuentra la cedula, se llenan los campos
                    txtNombre.setText(nombre);
                    cmbCurso.setSelectedItem(curso);
                    txtCalificacion.setText(String.valueOf(calificacion));
                    encontrado = true; // se encontro la cedula
                    break;//sale del bucle si encuentra al estudiante

                }

            }
            
        } catch (EOFException e) {
            //fin del archivo alcanzado
            if (!encontrado) {

                JOptionPane.showMessageDialog(null, "Error, estudiante no fue encontrado", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error al consultar los datos", "Error", JOptionPane.ERROR_MESSAGE);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error, calificacion no valida", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    
    public void eliminar() {
        String cedulaBuscar = txtCedula.getText();
        StringBuilder contenido = new StringBuilder();
        boolean encontrado = false;

        try (DataInputStream dis = new DataInputStream(new FileInputStream("Calificacion.dat"))) {
            while (true) {
                String cedula = dis.readUTF();
                String nombre = dis.readUTF();
                String curso = dis.readUTF();
                double calificacion = dis.readDouble();

                if (!cedula.equals(cedulaBuscar)) { // si la cedula del archivo No es igual a la buscada se conserva
                    //los guarda en un string - cadena
                contenido.append(cedula).append("\n").
                        append(nombre).append("\n").
                        append(curso).append("\n").
                        append(calificacion).append("\n");
                    

                }else{
                   encontrado = true; // se encontro la cedula 
                }
                
            }
        } catch (EOFException e) {
            //fin del archivo alcanzado

            if (encontrado) {
                guardarDatos(contenido.toString());
                JOptionPane.showMessageDialog(null, "Datos eliminados correctamente", "Datos eliminados", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Error, estudiante no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error al eliminar los datos", "Error", JOptionPane.ERROR_MESSAGE);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error, calificacion no valida", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    
    public void limpiar(){
        txtCedula.setText("");
        txtNombre.setText("");
        cmbCurso.setSelectedIndex(0);
        txtCalificacion.setText("");
        txtCedula.requestFocus();
        
    }


    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        agregar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        editar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        consultar();
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catalogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField txtCalificacion;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
