/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sem5gui;

import Conversor.Conversor;
import Estadistica.Registro;
import Saludador.Saludador;
import javax.swing.JOptionPane;

/**
 *
 * @author Randall Segura
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mitSaludar = new javax.swing.JMenuItem();
        mitConversor = new javax.swing.JMenuItem();
        mitRegistro = new javax.swing.JMenuItem();
        mitSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Soluciones Tecnologicas");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/robot.gif"))); // NOI18N

        jMenuBar1.setBackground(new java.awt.Color(0, 204, 204));
        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));

        jMenu1.setText("Opciones");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mitSaludar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mitSaludar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tecnica.png"))); // NOI18N
        mitSaludar.setText("Saludar");
        mitSaludar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitSaludarActionPerformed(evt);
            }
        });
        jMenu1.add(mitSaludar);

        mitConversor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mitConversor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tecnica.png"))); // NOI18N
        mitConversor.setText("Conversor");
        mitConversor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitConversorActionPerformed(evt);
            }
        });
        jMenu1.add(mitConversor);

        mitRegistro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mitRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tecnica.png"))); // NOI18N
        mitRegistro.setText("Registro");
        mitRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitRegistroActionPerformed(evt);
            }
        });
        jMenu1.add(mitRegistro);

        mitSalir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mitSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tecnica.png"))); // NOI18N
        mitSalir.setText("Salir");
        mitSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mitSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Acerca de...");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 629, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mitSaludarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitSaludarActionPerformed
        Saludador saludar= new Saludador();
        saludar.setVisible(true);
        saludar.setLocationRelativeTo(null);
    }//GEN-LAST:event_mitSaludarActionPerformed

    private void mitConversorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitConversorActionPerformed
        Conversor con= new Conversor();
        con.setVisible(true);
        con.setLocationRelativeTo(null);
    }//GEN-LAST:event_mitConversorActionPerformed

    private void mitRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitRegistroActionPerformed
        Registro reg= new Registro();
        reg.setVisible(true);
        reg.setLocationRelativeTo(null);
    }//GEN-LAST:event_mitRegistroActionPerformed

    private void mitSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitSalirActionPerformed

       JOptionPane.showMessageDialog(null,"Gracias por usar el sistema");
       System.exit(0);
    }//GEN-LAST:event_mitSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mitConversor;
    private javax.swing.JMenuItem mitRegistro;
    private javax.swing.JMenuItem mitSalir;
    private javax.swing.JMenuItem mitSaludar;
    // End of variables declaration//GEN-END:variables
}
