/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejemplo2;

import static Ejemplo2.Server.datainput;
import static Ejemplo2.Server.dataoutput;
import static Ejemplo2.Server.serversocket;
import static Ejemplo2.Server.socket;
import static Ejemplo2.Server.txaMostrar;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;

/**
 *
 * @author Usuario
 */
public class Cliente extends javax.swing.JFrame {

    //creacion de variables
    static Socket socket;
    static DataInputStream datainput;
    static DataOutputStream dataoutput;

    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
        //hacer el JFrame visible
        this.setVisible(true);
        //posicionar el JFrame
        this.setLocation(100, 100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMensaje = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaMostrar = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cliente");

        txtMensaje.setBackground(new java.awt.Color(255, 255, 255));
        txtMensaje.setForeground(new java.awt.Color(0, 0, 0));

        btnEnviar.setBackground(new java.awt.Color(0, 0, 0));
        btnEnviar.setForeground(new java.awt.Color(0, 51, 153));
        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chat con el Servidor");

        txaMostrar.setBackground(new java.awt.Color(255, 255, 255));
        txaMostrar.setColumns(20);
        txaMostrar.setForeground(new java.awt.Color(0, 0, 0));
        txaMostrar.setRows(5);
        jScrollPane1.setViewportView(txaMostrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnviar))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMensaje)
                    .addComponent(btnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        //bloque try en caso de que de una excepcion el catch lo captura
        try {
            //String msj="": Declaracion de variable donde se va a guardar el texto que se va a enviar de servidor a cliente.
            String msj = "";

            /*
            msj= txtMensaje.getText(): 
            Obtiene el texto que el usuario escribio en un campo de texto(txtMensaje) y lo guarda en msj.
             */
            msj = txtMensaje.getText();

            /*
            dataoutput.writeUTF(msj):
            Envia el contenido de msj a traves del DataOutputStream (dataoutput);
             */
            dataoutput.writeUTF(msj);

            /*
            txtMensaje.setText(""):
            Limpia el campo de texto despues de enviar el mensaje.
             */
            txtMensaje.setText("");

            /*
            txtMensaje.requestFocus():
            Devuelve el cursor al campo de texto txtMensaje 
             */
            txtMensaje.requestFocus();
            //el catch captura la exception en caso de que se de un error al enviar el mensaje 
        } catch (IOException e) {
            e.printStackTrace();

        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });

        /*creacion del hilo
         En el cliente, el hilo sirve para establecer la conexión con el servidor a través del Socket en un puerto específico,
         recibir y enviar mensajes en segundo plano y evitar que la interfaz gráfica (GUI) se congele mientras la comunicación está activa.
        */
        Thread hiloCli = new Thread(new Runnable() {
            public void run() {
                //bloque try en caso de errores
                try {
                    //String msjEntrante es para guardar el mensaje que llegue del servidor.
                    String msjEntrante = "";
                    
                    /*
                    socket = new Socket("127.0.0.1", 1201);
                    Crea un nuevo Socket para conectarse al servidor.
                    127.0.0.1 es la IP local (localhost).
                    1201 es el puerto donde el ServerSocket del servidor esta escuchando.
                    */
                    socket = new Socket("127.0.0.1", 1201);
                    /*
                    datainput = new DataInputStream(socket.getInputStream());
                    Prepara el canal de entrada para recibir datos del servidor.
                    */
                    datainput = new DataInputStream(socket.getInputStream());
                    /*
                    dataoutput = new DataOutputStream(socket.getOutputStream());
                    Prepara el canal de salida para enviar datos al servidor.
                    */
                    dataoutput = new DataOutputStream(socket.getOutputStream());
                    
                    /*
                    while (!msjEntrante.equals("exit")):
                    Bucle infinito mientras no se digite exit, si el servidor manda exit, se rompe el bucle y se detiene el hilo.
                    */
                    while (!msjEntrante.equals("exit")) {
                        
                        /*
                        msjEntrante = datainput.readUTF();
                        Espera y lee un mensaje del servidor.
                        */
                        msjEntrante = datainput.readUTF();
                        /*
                        txaMostrar.setText(txaMostrar.getText()+ "\nServidor: " + msjEntrante);
                        Muestra el mensaje recibido en un area de texto (txaMostrar).
                        Toma el texto actual, le agrega \nServidor: mensaje y actualiza el area.
                        De esta manera se construye un historial de navegacion.
                        */
                        txaMostrar.setText(txaMostrar.getText()+ "\nServidor: " + msjEntrante);
                    }
                    //el catch captura los posibles errores. 
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });
        /*
        hiloCli.start():
        Ejecuta el run() en paralelo con el resto de la app.
        De esta manera la interfaz grafica no se bloquea mientras se recibe informacion.
        */
        hiloCli.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea txaMostrar;
    private javax.swing.JTextField txtMensaje;
    // End of variables declaration//GEN-END:variables
}
