/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejemplo2;

import java.io.*;
import java.net.*;

/**
 *
 * @author Usuario
 */
public class Server extends javax.swing.JFrame {

    //creacion de variables
    static ServerSocket serversocket;
    static Socket socket;
    static DataInputStream datainput;
    static DataOutputStream dataoutput;

    /**
     * Creates new form Server
     */
    public Server() {
        initComponents();
        //hacer el JFrame visible
        this.setVisible(true);
        //posicionar el JFrame
        this.setLocation(100, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaMostrar = new javax.swing.JTextArea();
        txtMensaje = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Servidor");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Chat con el Cliente");

        txaMostrar.setBackground(new java.awt.Color(255, 255, 255));
        txaMostrar.setColumns(20);
        txaMostrar.setForeground(new java.awt.Color(0, 0, 0));
        txaMostrar.setRows(5);
        jScrollPane1.setViewportView(txaMostrar);

        txtMensaje.setBackground(new java.awt.Color(255, 255, 255));
        txtMensaje.setForeground(new java.awt.Color(0, 0, 0));

        btnEnviar.setBackground(new java.awt.Color(0, 0, 0));
        btnEnviar.setForeground(new java.awt.Color(0, 102, 0));
        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEnviar))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMensaje)
                    .addComponent(btnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed

        //bloque try en caso de que de una excepcion el catch lo captura
        try {

            //String msj="": Declaracion de variable donde se va a guardar el texto que se va a enviar de servidor a cliente.
            String msj = "";
            /*
            msj= txtMensaje.getText(): 
            Obtiene el texto que el usuario escribio en un campo de texto(txtMensaje) y lo guarda en msj.
             */
            msj = txtMensaje.getText();

            /*
            dataoutput.writeUTF(msj):
            Envia el contenido del msj a traves del DataOutputStream (dataoutput);
             */
            dataoutput.writeUTF(msj);

            /*
            txtMensaje.setText(""):
            Limpia el campo de texto despues de enviar el mensaje.
             */
            txtMensaje.setText("");

            /*
            txtMensaje.requestFocus():
            Devuelve el cursor al campo de texto txtMensaje 
             */
            txtMensaje.requestFocus();

            //el catch captura la exception en caso de que se de un error al enviar el mensaje 
        } catch (IOException e) {
            e.printStackTrace();

        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Server().setVisible(true);
            }
        });

        /*creacion del hilo 
        Significa que el codigo puede hacer varias cosas al mismo tiempo (concurrencia).
        El hilo sirve para que el servidor pueda aceptar conexiones y recibir mensajes en segundo plano, mientras la interfaz grafica,
        sigue viva y el usuario puede interactuar normalmente.
        El hilo sirve para que el servidor pueda aceptar conexiones de clientes y al mismo tiempo enviar y recibir mensajes en segundo plano,
        sin bloquear la interfaz gráfica (GUI). Si no se usa un hilo, el servidor se quedaría esperando una conexión (accept()) y la GUI se congelaría, 
        por lo que el cliente nunca lograría conectarse porque no podría interactuar con la ventana.
         */
        Thread hiloServ = new Thread(new Runnable() {
            public void run() {
                //bloque try en caso de errores
                try {
                    //String msjEntrante es para guardar el mensaje que llegue del cliente.
                    String msjEntrante = "";
                    /*
                    serversocket = new ServerSocket(1201);
                    Crea un ServerSocket que escucha en el puerto 1201, es la puerta de entrada para los clientes.
                     */
                    serversocket = new ServerSocket(1201);

                    /*
                    socket=serversocket.accept():
                    El ServerSocket espera hasta que un cliente se conecte 
                    Cuando llega un cliente, accept() le asigna un Socket (socket).
                    Ese Socket es el canal de comunicacion con el cliente.
                     */
                    socket = serversocket.accept();

                    /*
                    datainput = new DataInputStream(socket.getInputStream());
                    Prepara el canal de entrada para leer lo que el cliente envia.
                    Usa DataInputStream para leer los datos en UTF.
                     */
                    datainput = new DataInputStream(socket.getInputStream());

                    /*
                    dataoutput = new DataOutputStream(socket.getOutputStream());
                    Prepara el canal de salida para enviar datos al cliente.
                    DataOutputStream se usara para mandar respuestas en caso de querer responder.
                     */
                    dataoutput = new DataOutputStream(socket.getOutputStream());

                    /*
                    while (!msjEntrante.equals("exit")):
                    Bucle infinito mientras el mensaje recibido no sea exit.
                    Cuando el cliente digita exit, se romple el bucle y el hilo termina.
                     */
                    while (!msjEntrante.equals("exit")) {

                        /*
                        msjEntrante = datainput.readUTF();
                        En la variable se guarda y lee el mensaje del cliente
                         */
                        msjEntrante = datainput.readUTF();

                        /*
                        txaMostrar.setText(txaMostrar.getText() + "\nCliente: " + msjEntrante);
                        Muestra el mensaje recibido en un area de texto (txaMostrar).
                        Toma el texto actual, le agrega \nCliente: mensaje y actualiza el area.
                        De esta manera se construye un historial de navegacion. 
                         */
                        txaMostrar.setText(txaMostrar.getText() + "\nCliente: " + msjEntrante);

                    }
                    //el catch captura los posibles errores. 
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });
        /*
        hiloServ.start();
        Ejecuta el run() en paralelo con el resto de la app.
        De esta manera la interfaz grafica no se bloquea mientras se recibe informacion. 
         */
        hiloServ.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextArea txaMostrar;
    private javax.swing.JTextField txtMensaje;
    // End of variables declaration//GEN-END:variables
}
